names:
  '0': Storage Tank
  '1': Baseball field
  '10': Overpass
  '11': Expressway toll station
  '12': Train station
  '13': Chimney
  '14': Ground Track Field
  '15': Dam
  '16': Expressway service area
  '17': Stadium
  '18': Airport
  '19': Golf course
  '2': Tennis court
  '3': Basketball Court
  '4': Wind mill
  '5': Vehicle
  '6': Harbor
  '7': Ship
  '8': Airplane
  '9': Bridge
path: /kaggle/working
test: Model_Dataset/test/images
train: Model_Dataset/train/images
val: Model_Dataset/val/images
